#pragma once

#include <string>
#include <string_view>

// Text helpers specialised for Vietnamese. Everything in core works on std::u32string
// that is NFC and (for lookup keys) case-folded; these are the only functions allowed to
// produce such strings. No locale, no ICU: the tables cover exactly the Vietnamese
// alphabet (12 vowels x modifiers x 6 tones, plus đ) and are generated by
// tools/gen-text-tables/gen_vietnamese_tables.py.
//
// Threading: pure functions, safe on any thread, no allocation beyond the returned string.
namespace lankey::core::text {

// Compose combining tone/modifier marks into precomposed letters ("a" + U+0301 -> "á",
// "á" + U+0302 -> "ấ"). Marks that cannot combine with the preceding letter are kept as-is.
// Non-Vietnamese text passes through unchanged. Input that is already NFC is returned
// unchanged.
[[nodiscard]] std::u32string nfc(std::u32string_view s);

// Lowercase for ASCII letters and every precomposed Vietnamese letter. Other code points
// are unchanged. This is the case-fold used for lexicon keys ("Chương" and "chương" are
// the same entry).
[[nodiscard]] char32_t toLower(char32_t c) noexcept;
[[nodiscard]] char32_t toUpper(char32_t c) noexcept;
[[nodiscard]] std::u32string caseFold(std::u32string_view s);

// Remove tone marks and modifiers: "chương" -> "chuong", "đ" -> "d". Case is preserved.
[[nodiscard]] char32_t stripDiacritics(char32_t c) noexcept;
[[nodiscard]] std::u32string stripDiacritics(std::u32string_view s);

// True for letters of the Vietnamese alphabet in either case (a-z, đ, toned vowels).
// f, j, w, z are NOT Vietnamese letters but are accepted here because the engine passes
// them through in interleaved English; the "is this Vietnamese" question belongs to the
// dictionary, not to the alphabet check.
[[nodiscard]] bool isLetter(char32_t c) noexcept;
[[nodiscard]] bool isAllLetters(std::u32string_view s) noexcept;

// True when the letter carries a tone mark or modifier (ă â ê ô ơ ư đ or any toned vowel).
[[nodiscard]] bool hasDiacritic(char32_t c) noexcept;
// True when the letter carries a TONE mark (sắc huyền hỏi ngã nặng); modifiers alone
// (ă â ê ô ơ ư đ) do not count. A syllable has a tone when any of its letters does.
[[nodiscard]] bool hasTone(char32_t c) noexcept;
[[nodiscard]] bool hasTone(std::u32string_view s) noexcept;

// Re-apply the casing pattern of `typed` to the folded `folded`: "Chư" -> "Chương",
// "CHƯ" -> "CHƯƠNG", "chư" -> "chương". A single capital counts as capitalised.
[[nodiscard]] std::u32string applyCasing(std::u32string_view typed, std::u32string_view folded);

} // namespace lankey::core::text
