#!/usr/bin/env python3
"""Generate core/text/VietnameseTables.inc from Unicode data.

The IME only ever deals with Vietnamese letters, so instead of shipping full Unicode
normalisation tables we generate the tiny subset needed:

  kCompose:   (base or partially composed letter, combining mark) -> precomposed letter
  kLetters:   every precomposed Vietnamese letter -> {lowercase form, uppercase form,
              base letter without any diacritic}

Run:  python tools/gen-text-tables/gen_vietnamese_tables.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent.parent / "core" / "text" / "VietnameseTables.inc"

BASE_VOWELS = "aeiouy"
# Modifier marks (applied first) and tone marks (applied last), as combining code points.
MODIFIERS = {"̂": "circumflex", "̆": "breve", "̛": "horn"}
TONES = {"̀": "grave", "́": "acute", "̃": "tilde", "̉": "hook", "̣": "dot"}

# Which modifier applies to which base vowel (ă â ê ô ơ ư).
MOD_FOR = {
    "a": ["̂", "̆"],
    "e": ["̂"],
    "o": ["̂", "̛"],
    "u": ["̛"],
    "i": [],
    "y": [],
}


def nfc(s: str) -> str:
    return unicodedata.normalize("NFC", s)


def build() -> tuple[dict[tuple[str, str], str], dict[str, tuple[str, str, str]]]:
    compose: dict[tuple[str, str], str] = {}
    letters: dict[str, tuple[str, str, str]] = {}  # letter -> (lower, upper, base)

    def add_letter(ch: str, base: str) -> None:
        letters[ch] = (ch.lower(), ch.upper(), base)
        letters[ch.upper()] = (ch, ch.upper(), base.upper())

    for v in BASE_VOWELS:
        # plain vowel with each tone
        for tone in TONES:
            c = nfc(v + tone)
            assert len(c) == 1, (v, tone)
            compose[(v, tone)] = c
            compose[(v.upper(), tone)] = c.upper()
            add_letter(c, v)
        # modified vowel, then with each tone
        for mod in MOD_FOR[v]:
            m = nfc(v + mod)
            assert len(m) == 1
            compose[(v, mod)] = m
            compose[(v.upper(), mod)] = m.upper()
            add_letter(m, v)
            for tone in TONES:
                c = nfc(m + tone)
                assert len(c) == 1, (m, tone)
                compose[(m, tone)] = c
                compose[(m.upper(), tone)] = c.upper()
                # Tone typed before the modifier still composes in NFC ("á" + "̂" -> "ấ").
                toned = nfc(v + tone)
                compose[(toned, mod)] = c
                compose[(toned.upper(), mod)] = c.upper()
                add_letter(c, v)
        add_letter(v, v)

    # đ has no combining form worth composing; it is just a letter with a base.
    add_letter("đ", "d")
    for ch in "bcdfghjklmnpqrstvwxz":
        add_letter(ch, ch)
    return compose, letters


def cp(ch: str) -> str:
    return f"0x{ord(ch):04X}"


def main() -> int:
    compose, letters = build()
    lines = [
        "// Generated by tools/gen-text-tables/gen_vietnamese_tables.py - do not edit.",
        "// clang-format off",
        "",
        "// (first, combining mark) -> precomposed",
        "inline constexpr ComposeEntry kCompose[] = {",
    ]
    for (a, b), c in sorted(compose.items(), key=lambda kv: (ord(kv[0][0]), ord(kv[0][1]))):
        lines.append(f"    {{{cp(a)}, {cp(b)}, {cp(c)}}},  // {a}+{unicodedata.name(b).split()[-1].lower()} -> {c}")
    lines += ["};", "", "// letter -> {lowercase, uppercase, base letter without diacritics}",
              "inline constexpr LetterEntry kLetters[] = {"]
    for ch, (lower, upper, base) in sorted(letters.items(), key=lambda kv: ord(kv[0])):
        lines.append(f"    {{{cp(ch)}, {cp(lower)}, {cp(upper)}, {cp(base)}}},  // {ch} -> {lower}, {upper}, {base}")
    lines += ["};", "", "// clang-format on", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{len(compose)} compose entries, {len(letters)} letters -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
