#!/usr/bin/env python3
"""Generate width-pairs.tsv: the authoritative half-width <-> full-width table.

The pairs come from the Unicode character database (NFKC/NFKD), not from LanKey's own
table, so tests/unit/width_converter_test.cpp checks the implementation against the
standard rather than against itself. Two deliberate deviations are recorded here with a
"note" column; they are what Windows IMEs and every Japanese text tool do:

  * A lone half-width voiced mark ﾞ/ﾟ (U+FF9E/U+FF9F) becomes the SPACING mark ゛/゜
    (U+309B/U+309C), not the combining mark U+3099/U+309A that NFKC produces. A combining
    mark would attach itself to whatever character precedes it in the document.
  * Full-width forms whose half-width counterpart is not ASCII (U+FFE0..U+FFE6: ￠￡￢￣￤￥
    and the half-width symbols U+FFE8..U+FFEE) are left alone: they are not part of the
    ASCII/katakana conversion a user means by 全角/半角.

Usage: python tests/data/make_width_pairs.py   (writes width-pairs.tsv next to itself)
"""

import unicodedata
from pathlib import Path

OUT = Path(__file__).with_name("width-pairs.tsv")


def nfkc(s: str) -> str:
    return unicodedata.normalize("NFKC", s)


def nfkd(s: str) -> str:
    return unicodedata.normalize("NFKD", s)


def hexes(s: str) -> str:
    return " ".join(f"{ord(c):04X}" for c in s)


def main() -> None:
    rows = []  # (half, full, note)

    # ASCII and space. NFKC of a full-width form is its ASCII counterpart; the reverse is
    # the unique full-width form that normalises back to it.
    for cp in range(0x21, 0x7F):
        full = chr(cp + 0xFEE0)
        assert nfkc(full) == chr(cp), (hex(cp), hexes(nfkc(full)))
        rows.append((chr(cp), full, "ascii"))
    assert nfkc("　") == " "
    rows.append((" ", "　", "space"))

    # Latin-1 symbols that have a full-width form (U+FFE0..U+FFE5). Windows converts these
    # too, and ￥ in particular is everywhere in Japanese text. U+FFE6 ￦ (Korean won) and
    # U+FFE8..U+FFEE (half-width line/arrow/shape symbols) are left out: not part of the
    # ASCII/katakana conversion, and Windows does not convert the latter either.
    # (One level of compatibility decomposition, not NFKC: ￣ decomposes to ¯, which NFKC
    # would then decompose again into space + combining macron.)
    for full_cp in range(0xFFE0, 0xFFE6):
        full = chr(full_cp)
        tag, _, target = unicodedata.decomposition(full).partition(" ")
        assert tag == "<wide>", (hex(full_cp), unicodedata.decomposition(full))
        half = chr(int(target, 16))
        assert ord(half) < 0x100, (hex(full_cp), hexes(half))
        rows.append((half, full, "symbol"))

    # Half-width katakana. NFKC maps each to its full-width form, combining a following
    # voiced mark where one exists (ｶ + ﾞ -> ガ).
    for cp in range(0xFF61, 0xFFA0):
        half = chr(cp)
        if cp in (0xFF9E, 0xFF9F):  # lone voiced marks: spacing form, see the docstring
            rows.append((half, "゛" if cp == 0xFF9E else "゜", "mark-spacing"))
            continue
        full = nfkc(half)
        assert len(full) == 1, (hex(cp), hexes(full))
        rows.append((half, full, "kana"))

        # ... and the voiced/semi-voiced combinations, when Unicode has a single character
        # for them (ｶﾞ -> ガ, ﾊﾟ -> パ, ｳﾞ -> ヴ, ﾜﾞ -> ヷ).
        for mark, kind in ((0xFF9E, "dakuten"), (0xFF9F, "handakuten")):
            combined = nfkc(half + chr(mark))
            if len(combined) == 1 and combined != full:
                rows.append((half + chr(mark), combined, kind))

    # Every full-width form must be unique: two half-width spellings mapping to the same
    # character would make the reverse direction ambiguous.
    seen = {}
    for half, full, note in rows:
        assert full not in seen, (hexes(full), seen[full], half)
        seen[full] = half

    # Sanity: the reverse of each pair is what NFKD says it decomposes to.
    for half, full, note in rows:
        if note in ("dakuten", "handakuten"):
            decomposed = nfkd(full)
            assert len(decomposed) == 2, (hexes(full), hexes(decomposed))

    lines = [
        "# half<TAB>full<TAB>note - generated by make_width_pairs.py from Unicode "
        f"{unicodedata.unidata_version}. Do not edit by hand.",
    ]
    for half, full, note in rows:
        lines.append(f"{hexes(half)}\t{hexes(full)}\t{note}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT} with {len(rows)} pairs")


if __name__ == "__main__":
    main()
