#!/usr/bin/env python3
"""Build data/vi_base_syllables.txt - the closed set of valid Vietnamese syllables.

This is the BaseSyllableSet source: AutoCorrect treats a syllable that is
NOT in this set as a probable typo, so the list must contain only real Vietnamese
syllables and nothing else (no abbreviations, no loanwords, no proper-noun-only
capitalisation).

Sources are listed in SOURCES.md. Run from anywhere:

    python tools/build-dictionary/build_syllables.py

Output: one syllable per line, NFC, lowercase, sorted by code point, UTF-8, LF.
Both tone-mark placements (classic "hòa" and modern "hoà") are included because the
engine emits whichever one the user configured and the set is compared against engine
output verbatim.
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SOURCES = HERE / "sources" / "hunspell-vi"
OUTPUT = ROOT / "data" / "vi_base_syllables.txt"

# The Vietnamese alphabet: 29 letters, 12 vowels x 6 tones. f, j, w, z are not letters
# of Vietnamese; their presence marks a loanword or abbreviation.
VOWELS_BASE = "aăâeêioôơuưy"
TONED = (
    "àảãáạ" "ằẳẵắặ" "ầẩẫấậ" "èẻẽéẹ" "ềểễếệ" "ìỉĩíị"
    "òỏõóọ" "ồổỗốộ" "ờởỡớợ" "ùủũúụ" "ừửữứự" "ỳỷỹýỵ"
)
CONSONANTS = "bcdđghklmnpqrstvx"
VOWELS = frozenset(VOWELS_BASE + TONED)
ALPHABET = frozenset(VOWELS_BASE + TONED + CONSONANTS)

# Entries in hunspell-vi that are real dictionary headwords but not Vietnamese
# syllables. All-caps abbreviations are dropped by a separate rule in main(); these are
# the lowercase/capitalised leftovers. Keep this list explicit so a source update cannot
# silently add new loanwords.
LOANWORDS = {
    "web", "internet", "intranet", "unicode", "telex", "tp",
}

# Longest real syllable is 7 letters ("nghiêng", "trường"); anything longer is a
# multi-syllable or foreign entry that slipped through.
MAX_LEN = 7


def read_dic(path: Path) -> list[str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    # First line of a Hunspell .dic is the entry count.
    return [ln.split("/")[0].strip() for ln in lines[1:] if ln.strip()]


def is_syllable(word: str) -> bool:
    if not word or len(word) > MAX_LEN:
        return False
    if word in LOANWORDS:
        return False
    if not all(ch in ALPHABET for ch in word):
        return False
    # Every syllable has a nucleus; a consonant-only entry ("v" as in "v.v.") is not one.
    return any(ch in VOWELS for ch in word)


def main() -> int:
    raw: set[str] = set()
    for name in ("vi-DauMoi.dic", "vi-DauCu.dic"):
        raw.update(read_dic(SOURCES / name))

    kept: set[str] = set()
    dropped: list[str] = []
    for word in raw:
        # All-caps entries are abbreviations (HTML, UBND, TCVN); capitalised ones are
        # proper nouns whose syllable is still valid Vietnamese (Huế, Nguyễn).
        if len(word) > 1 and word.isupper():
            dropped.append(word)
            continue
        w = unicodedata.normalize("NFC", word).lower()
        if is_syllable(w):
            kept.add(w)
        else:
            dropped.append(word)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# vi_base_syllables - generated by tools/build-dictionary/build_syllables.py\n")
        f.write("# Sources and licenses: tools/build-dictionary/SOURCES.md. Do not edit by hand.\n")
        for w in sorted(kept):
            f.write(w + "\n")

    print(f"raw entries: {len(raw)}")
    print(f"kept: {len(kept)}  -> {OUTPUT.relative_to(ROOT)}")
    print(f"dropped ({len(dropped)}): {' '.join(sorted(dropped))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
